name:                gameoflife
version:             0.1.0.0
github:              "githubuser/gameoflife"
license:             BSD3
author:              "Archibald Neil MacDonald"
maintainer:          "FortOyer@hotmail.co.uk"
copyright:           "2018 Archibald Neil MacDonald"

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on Github at <https://github.com/FortOyer/gameoflife#readme>

dependencies:
- base == 4.9.*
- reactive-banana
- reactive-banana-wx
- wx
- wxc
- wxcore
- array

library:
  source-dirs: src

executables:
  gameoflife-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gameoflife
